var idx = 0;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "BATTLESHIP");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 38;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "CANNONBOAT");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "BLACK_BOAT");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 85;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "CRUISER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 20;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "DESTROYER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 28;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "SUBMARINE");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 95;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "LANDER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 40;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "AIRCRAFTCARRIER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 38;
