WEAPON_PIPERUNNER_MISSILE.getEnviromentDamage = function(enviromentId)
{
    return 55;
};
var idx = 0;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE.damageTable, "INFANTRY");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "MECH");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "MOTORBIKE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "SNIPER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 95;

// supporter
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "APC");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "FLARE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "RECON");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 90;

// tanks
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "FLAK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "HOVERFLAK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "LIGHT_TANK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "HOVERCRAFT");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 80;

// heavy tanks
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "HEAVY_HOVERCRAFT");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "HEAVY_TANK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "NEOTANK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 50;

// very heavy tanks
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "MEGATANK");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 25;

idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "HOELLIUM");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 15;

// heli copter
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "T_HELI");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 115;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "K_HELI");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 115;

//air
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "DUSTER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 100;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "FIGHTER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 100;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "BOMBER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 100;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "STEALTHBOMBER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 100;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "TRANSPORTPLANE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "BLACK_BOMB");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "WATERPLANE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 100;

// ranged land units
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "ARTILLERY");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_A_TANK_CANNON.damageTable, "ARTILLERYCRAFT");
WEAPON_A_TANK_CANNON.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "ANTITANKCANNON");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "MISSILE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "ROCKETTHROWER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "PIPERUNNER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 80;

// ships
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "BATTLESHIP");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "CANNONBOAT");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "CRUISER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "DESTROYER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "SUBMARINE");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "LANDER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "BLACK_BOAT");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_PIPERUNNER_MISSILE, "AIRCRAFTCARRIER");
WEAPON_PIPERUNNER_MISSILE.damageTable[idx][1] = 60;
