WEAPON_HEAVY_HOVERCRAFT_GUN.getEnviromentDamage = function(enviromentId)
{
    return 55;
};
var idx = 0;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable, "APC");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "FLARE");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "RECON");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;

// tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "FLAK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "HOVERFLAK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "LIGHT_TANK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "HOVERCRAFT");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 85;

// heavy tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "HEAVY_HOVERCRAFT");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "HEAVY_TANK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "NEOTANK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 45;

// very heavy tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "MEGATANK");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 25;

idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "HOELLIUM");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 30;

// ranged land units
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "ARTILLERY");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "ANTITANKCANNON");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "MISSILE");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "ROCKETTHROWER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "PIPERUNNER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 85;

// ships
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "BATTLESHIP");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 10;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "CANNONBOAT");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "CRUISER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 30;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "DESTROYER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 30;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "SUBMARINE");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 10;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "LANDER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "BLACK_BOAT");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_GUN, "AIRCRAFTCARRIER");
WEAPON_HEAVY_HOVERCRAFT_GUN.damageTable[idx][1] = 10;
