WEAPON_STEALTHROCKET.getEnviromentDamage = function(enviromentId)
{
    return 70;
};
var idx = 0;
idx = getIndexOf1(WEAPON_STEALTHROCKET.damageTable, "INFANTRY");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "MECH");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "MOTORBIKE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "SNIPER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 90;

// supporter
idx = getIndexOf1(WEAPON_STEALTHROCKET, "APC");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "FLARE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "RECON");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 85;

// tanks
idx = getIndexOf1(WEAPON_STEALTHROCKET, "FLAK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "HOVERFLAK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "LIGHT_TANK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "HOVERCRAFT");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;

// heavy tanks
idx = getIndexOf1(WEAPON_STEALTHROCKET, "HEAVY_HOVERCRAFT");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 70;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "HEAVY_TANK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 70;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "NEOTANK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 60;

// very heavy tanks
idx = getIndexOf1(WEAPON_STEALTHROCKET, "MEGATANK");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 25;

idx = getIndexOf1(WEAPON_STEALTHROCKET, "HOELLIUM");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 30;

// ranged land units
idx = getIndexOf1(WEAPON_STEALTHROCKET, "ARTILLERY");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_A_TANK_CANNON.damageTable, "ARTILLERYCRAFT");
WEAPON_A_TANK_CANNON.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "ANTITANKCANNON");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "MISSILE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "ROCKETTHROWER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "PIPERUNNER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 80;

// air units
idx = getIndexOf1(WEAPON_STEALTHROCKET, "DUSTER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "FIGHTER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "BOMBER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "STEALTHBOMBER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "TRANSPORTPLANE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "BLACK_BOMB");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "WATERPLANE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "K_HELI");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 115;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "T_HELI");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 115;


// ships
idx = getIndexOf1(WEAPON_STEALTHROCKET, "BATTLESHIP");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "CANNONBOAT");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "CRUISER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "DESTROYER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "SUBMARINE");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "LANDER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "BLACK_BOAT");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_STEALTHROCKET, "AIRCRAFTCARRIER");
WEAPON_STEALTHROCKET.damageTable[idx][1] = 60;
