WEAPON_HEAVY_HOVERCRAFT_MG.getEnviromentDamage = function(enviromentId)
{
    WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;
};
var idx = 0;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG.damageTable, "INFANTRY");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "MECH");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "MOTORBIKE");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "SNIPER");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 95;

// supporter
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "APC");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "FLARE");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "RECON");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 45;

// tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "FLAK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 7;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "HOVERFLAK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 7;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "LIGHT_TANK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 8;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "HOVERCRAFT");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 8;

// heavy tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "HEAVY_HOVERCRAFT");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "HEAVY_TANK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "NEOTANK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;

// very heavy tanks
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "MEGATANK");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;

idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "HOELLIUM");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 20;

// heli copter
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "T_HELI");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "K_HELI");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 12;

// ranged land units
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "ARTILLERY");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "ANTITANKCANNON");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 1;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "MISSILE");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 35;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "ROCKETTHROWER");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_HEAVY_HOVERCRAFT_MG, "PIPERUNNER");
WEAPON_HEAVY_HOVERCRAFT_MG.damageTable[idx][1] = 8;
