WEAPON_WATERPLANE_MISSILE.getEnviromentDamage = function(enviromentId)
{
    return 45;
};
var idx = 0;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE.damageTable, "INFANTRY");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "MECH");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "MOTORBIKE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "SNIPER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 85;

// supporter
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "APC");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "FLARE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "RECON");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 80;

// tanks
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "FLAK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "HOVERFLAK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "LIGHT_TANK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "HOVERCRAFT");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 75;

// heavy tanks
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "HEAVY_HOVERCRAFT");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "HEAVY_TANK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "NEOTANK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 65;

// very heavy tanks
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "MEGATANK");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 55;

idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "HOELLIUM");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 20;

// ranged land units
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "ARTILLERY");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 70;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "ANTITANKCANNON");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "MISSILE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 70;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "ROCKETTHROWER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "PIPERUNNER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 70;

idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "DUSTER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "FIGHTER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "BOMBER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "STEALTHBOMBER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "TRANSPORTPLANE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "BLACK_BOMB");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "WATERPLANE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "K_HELI");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "T_HELI");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 95;

// ships
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "BATTLESHIP");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "CANNONBOAT");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "CRUISER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 40;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "DESTROYER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 40;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "SUBMARINE");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "LANDER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_WATERPLANE_MISSILE, "AIRCRAFTCARRIER");
WEAPON_WATERPLANE_MISSILE.damageTable[idx][1] = 65;
