WEAPON_BATTLESHIP_CANNON.getEnviromentDamage = function(enviromentId)
{
    return 55;
};
var idx = 0;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON.damageTable, "INFANTRY");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "MECH");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "MOTORBIKE");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "SNIPER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 90;

// supporter
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "APC");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 60;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "FLARE");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 90;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "RECON");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 90;

// tanks
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "FLAK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "HOVERFLAK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "LIGHT_TANK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "HOVERCRAFT");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 80;

// heavy tanks
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "HEAVY_HOVERCRAFT");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "HEAVY_TANK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "NEOTANK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 50;

// very heavy tanks
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "MEGATANK");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 25;

// ranged land units
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "ARTILLERY");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_A_TANK_CANNON.damageTable, "ARTILLERYCRAFT");
WEAPON_A_TANK_CANNON.damageTable[idx][1] = 80;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "ANTITANKCANNON");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "MISSILE");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "ROCKETTHROWER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 85;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "PIPERUNNER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 80;

idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "HOELLIUM");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 20;

// ships
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "BATTLESHIP");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "CANNONBOAT");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "CRUISER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "DESTROYER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "SUBMARINE");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "LANDER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "BLACK_BOAT");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_BATTLESHIP_CANNON, "AIRCRAFTCARRIER");
WEAPON_BATTLESHIP_CANNON.damageTable[idx][1] = 60;
