var idx = 0;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON.damageTable, "BATTLESHIP");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "CANNONBOAT");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 95;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "CRUISER");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "DESTROYER");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "SUBMARINE");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 65;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "LANDER");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "BLACK_BOAT");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 95;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CANNON, "AIRCRAFTCARRIER");
WEAPON_ANTI_SHIP_CANNON.damageTable[idx][1] = 75;
