WEAPON_HOVERVULCAN_CANNON.getEnviromentDamage = function(enviromentId)
{
    return 1;
};
var idx = 0;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON.damageTable, "INFANTRY");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "MECH");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "MOTORBIKE");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "SNIPER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;

// supporter
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "APC");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "FLARE");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "RECON");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 60;

// tanks
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "FLAK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "HOVERFLAK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 45;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "LIGHT_TANK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "HOVERCRAFT");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 25;

// heavy tanks
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "HEAVY_HOVERCRAFT");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 10;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "HEAVY_TANK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 10;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "NEOTANK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 5;

// very heavy tanks
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "MEGATANK");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 1;

idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "HOELLIUM");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 30;

// heli copter
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "T_HELI");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "K_HELI");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 105;

//air
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "DUSTER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "FIGHTER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 65;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "BOMBER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "STEALTHBOMBER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 75;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "BLACK_BOMB");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "TRANSPORTPLANE");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 120;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "WATERPLANE");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 75;

// ranged land units
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "ARTILLERY");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_A_TANK_CANNON.damageTable, "ARTILLERYCRAFT");
WEAPON_A_TANK_CANNON.damageTable[idx][1] = 50;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "ANTITANKCANNON");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "MISSILE");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "ROCKETTHROWER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 55;
idx = getIndexOf1(WEAPON_HOVERVULCAN_CANNON, "PIPERUNNER");
WEAPON_HOVERVULCAN_CANNON.damageTable[idx][1] = 25;
