var idx = 0;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "BATTLESHIP");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 5;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "CANNONBOAT");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 25;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "CRUISER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "DESTROYER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "SUBMARINE");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 90;

idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "LANDER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "BLACK_BOAT");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 25;
idx = getIndexOf1(WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable, "AIRCRAFTCARRIER");
WEAPON_ANTI_SHIP_CRUISER_MISSILE.damageTable[idx][1] = 5;
