name: Tests
on: [push]
env:
  BUILD_TYPE: Debug
  QT_Version: '6.10.3'

jobs:
  tests:
    name: Build and run tests
    strategy:
      fail-fast: false
      matrix:
        buildTarget: [ubuntu, windows, macos]
        include:
          - buildTarget: ubuntu
            os: ubuntu-latest
            qtArch: ''
            qtDir: 'gcc_64'
            qtTools: ''
            installerCommands1: 'sudo apt-get update'
            installerCommands2: 'sudo apt-get install -y libxcb-cursor0 libgl1-mesa-dri libegl1 libopengl0'
            cmakeOptions: '-DOPENSSL_USE_STATIC_LIBS=FALSE'
          - buildTarget: macos
            os: macos-15
            qtArch: 'clang_64'
            qtDir: 'clang_64'
            qtTools: ''
            installerCommands1: ''
            installerCommands2: ''
            cmakeOptions: '-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'

    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout source code
      uses: actions/checkout@v7
      with:
          path: 'source'
          submodules: 'true'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
          target: 'desktop'
          version: ${{env.QT_Version}}
          arch: ${{matrix.qtArch}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          tools: '${{matrix.qtTools}}'
          set-env: 'true'

    - name: Install OS Dependencies 1
      run: ${{matrix.installerCommands1}}

    - name: Install OS Dependencies 2
      run: ${{matrix.installerCommands2}}

    - name: Configure tests cmake
      run: |
        cmake \
        -S "${{github.workspace}}/source/tests" \
        -B "${{github.workspace}}/build_tests" \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtDir}}/" \
        -DQt6_DIR=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtDir}}/lib/cmake/Qt6/ \
        ${{matrix.cmakeOptions}}

    - name: Build tests
      run: cmake --build '${{github.workspace}}/build_tests' -j4

    - name: Run tests
      working-directory: '${{github.workspace}}/build_tests'
      env:
        QT_QPA_PLATFORM: offscreen
      run: ctest --output-on-failure -V
